Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
 
  config.vm.define "aaubertiS" do |machine|
    machine.vm.hostname = "aaubertiS"
    machine.vm.network "private_network", ip: "192.168.56.110"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "aaubertiS"
      vb.cpus = 1
      vb.memory = 1024
    end
    
    machine.vm.provision "shell", inline: <<-SHELL
      
      until ip addr | grep -q "192.168.56.110"; do
        sleep 2
      done
      
      IFACE=$(ip -o addr show | grep "192.168.56.110" | awk '{print $2}')
      
      curl -sfL https://get.k3s.io | sh -s - \
        --node-ip=192.168.56.110 \
        --flannel-iface=$IFACE
      
      until [ -f /var/lib/rancher/k3s/server/node-token ]; do
        sleep 3
      done
      
      sudo cat /var/lib/rancher/k3s/server/node-token > /vagrant/k3s-token
    SHELL
  end
  
  config.vm.define "aaubertiSW" do |machine|
    machine.vm.hostname = "aaubertiSW"
    machine.vm.network "private_network", ip: "192.168.56.111"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "aaubertiSW"
      vb.cpus = 1
      vb.memory = 1024
    end
    
    machine.vm.provision "shell", inline: <<-SHELL
      
      while [ ! -f /vagrant/k3s-token ]; do
        sleep 2
      done
      
      until ip addr | grep -q "192.168.56.111"; do
        sleep 2
      done
      
      IFACE=$(ip -o addr show | grep "192.168.56.111" | awk '{print $2}')
      
      K3S_TOKEN=$(cat /vagrant/k3s-token)
      curl -sfL https://get.k3s.io | K3S_URL=https://192.168.56.110:6443 \
        K3S_TOKEN=$K3S_TOKEN sh -s - agent \
        --node-ip=192.168.56.111 \
        --flannel-iface=$IFACE
      
    SHELL
  end
end
