Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
 
  config.vm.define "aaubertiS" do |machine|
    machine.vm.hostname = "aaubertiS"
    machine.vm.network "private_network", ip: "192.168.56.110"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "aaubertiS"
      vb.cpus = 1
      vb.memory = 1024
    end
    
    machine.vm.provision "shell", inline: <<-SHELL
      curl -sfL https://get.k3s.io | sudo sh -s - \
      --node-ip=192.168.56.110 \
      --write-kubeconfig-mode 664

      kubectl apply -f /vagrant/manifest/app1/app1-deployment.yaml
      kubectl apply -f /vagrant/manifest/app2/app2-deployment.yaml
      kubectl apply -f /vagrant/manifest/app3/app3-deployment.yaml
      kubectl apply -f /vagrant/manifest/app1/app1-service.yaml
      kubectl apply -f /vagrant/manifest/app2/app2-service.yaml
      kubectl apply -f /vagrant/manifest/app3/app3-service.yaml
      kubectl apply -f /vagrant/manifest/ingress.yaml
    SHELL
  end
end
