Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
 
  config.vm.define "aaubertiS" do |machine|
    machine.vm.hostname = "aaubertiS"
    machine.vm.network "private_network", ip: "192.168.56.110"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "aaubertiS"
      vb.cpus = 1
      vb.memory = 1024
    end
    
    machine.vm.provision "shell", inline: <<-SHELL
      curl -sfL https://get.k3s.io | sudo sh -s - \
      --node-ip=192.168.56.110 \
      --write-kubeconfig-mode 664
    SHELL
    end
  end
