Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
 
  config.vm.define "antauberS" do |machine|
    machine.vm.hostname = "antauberS"
    machine.vm.network "private_network", ip: "192.168.56.110"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "antauberS"
      vb.cpus = 1
      vb.memory = 1024
    end
    
    machine.vm.provision "shell", path: "scripts/server.sh"
  end
  
  config.vm.define "antauberSW" do |machine|
    machine.vm.hostname = "antauberSW"
    machine.vm.network "private_network", ip: "192.168.56.111"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "antauberSW"
      vb.cpus = 1
      vb.memory = 1024
    end
    
    machine.vm.provision "shell", path: "scripts/worker.sh"
  end
end
