Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
 
  config.vm.define "aaubertiS" do |machine|
    machine.vm.hostname = "aaubertiS"
    machine.vm.network "private_network", ip: "192.168.56.110"
    machine.vm.provider "virtualbox" do |vb|
      #vb.customize ["modifyvm", :id, "--name", "aaubertiS"]
      vb.name = "aaubertiS"
      vb.cpus = 1
      vb.memory = 1024
    end
    machine.vm.provision "shell", inline: <<-SHELL
      curl -sfL https://get.k3s.io | sh -
      until [ -f /var/lib/rancher/k3s/server/node-token ]; do
        sleep 3;
      done
      sudo cat /var/lib/rancher/k3s/server/node-token > /vagrant/k3s-token
    SHELL

  end
  config.vm.define "aaubertiSW" do |machine|
    machine.vm.hostname = "aaubertiSW"
    machine.vm.network "private_network", ip: "192.168.56.111"
    machine.vm.provider "virtualbox" do |vb|
      #vb.customize ["modifyvm", :id, "--name", "aaubertiSW"]
      vb.name = "aaubertiSW"
      vb.cpus = 1
      vb.memory = 1024
    end
    machine.vm.provision "shell", inline: <<-SHELL
     while [ ! -f /vagrant/k3s-token ]; do
      echo coucou....................
       sleep 2;
     done

     K3S_TOKEN=$(cat /vagrant/k3s-token)
     curl -sfL https://get.k3s.io | K3S_URL=https://192.168.56.110:6443 \
     K3S_TOKEN=$K3S_TOKEN sh -s - agent
    SHELL
  end
end    
